# Надбавки за плотность товара к базовому тарифу логистики
# Источник: Расчеты Хай Вэй NEW - Плохая плотность.csv
# Обновлено: 06.10.2025

# Формат: плотность (кг/м³) → надбавка ($)
# Логика: Итоговая ставка = Базовая ставка + Надбавка за плотность

density_surcharges:
  # ЗЕМЛЯ (ЖД) - Надбавка к базовому тарифу
  rail:
    5: 63.00
    10: 30.60
    15: 19.80
    20: 14.40
    25: 11.16
    30: 9.00
    35: 7.46
    40: 6.30
    45: 5.40
    50: 4.68
    55: 4.09
    60: 3.60
    65: 3.18
    70: 2.83
    75: 2.52
    80: 2.25
    85: 2.01
    90: 1.80
    95: 1.61
    100: 1.44
    105: 1.29
    110: 1.15
    115: 1.02
    120: 0.90
    125: 0.79
    130: 0.69
    135: 0.60
    140: 0.51
    145: 0.43
    150: 0.36
    155: 0.29
    160: 0.23
    165: 0.16
    170: 0.11
    175: 0.05
    180: 0.00  # От 180 кг/м³ и выше - без надбавки
    
  # АВИА - Надбавка к базовому тарифу
  air:
    6: 104.65
    13: 46.20
    20: 28.67
    27: 20.22
    34: 15.26
    41: 11.99
    48: 9.67
    55: 7.94
    62: 6.60
    69: 5.54
    76: 4.67
    83: 3.95
    90: 3.34
    97: 2.81
    104: 2.36
    111: 1.97
    118: 1.62
    125: 1.31
    132: 1.03
    139: 0.79
    146: 0.56
    153: 0.36
    160: 0.17
    167: 0.00  # От 167 кг/м³ и выше - без надбавки

# Примеры использования:
# 
# Пример 1: ЖД, плотность 85 кг/м³
# Базовая ставка: $6.10/кг
# Надбавка: +$2.01/кг
# Итого: $8.11/кг
#
# Пример 2: Авиа, плотность 50 кг/м³
# Базовая ставка: $10.50/кг
# Надбавка: +$9.67/кг (интерполяция между 48 и 55)
# Итого: $20.17/кг
#
# Примечание: 
# - Для промежуточных значений используется линейная интерполяция
# - Чем ниже плотность, тем выше надбавка (легкие товары дороже в перевозке)
# - При плотности выше максимальной (180 для ЖД, 167 для Авиа) надбавка = 0











