[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd web_interface && gunicorn -c gunicorn_config.py app:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
