[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd web_interface && gunicorn -w 4 -b :$PORT app:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
